# IIlustration of the Model based Reinforcement Learning Techniques -- Value Iteration, Policy Iteration -- with deterministic and stochastic environments in Frozen Lake problem

In [1]:
import gym
import numpy as np

# Value Iteration 
Steps: <br>
1. Initialize Value Function <br>
2. Repeat <br>
    a. Find Q(state,action) from the value Function <br> 
    $$q(s,a) = R_{s}^{a} + \sum P_{ss^{'}}^{a}v_{\pi}(s^{'})$$ <br>
    b. Update Value Function <br> 
    $$v_{\pi}(s) = \max_a {q(s,a)}$$
3. Find Policy from value function <br>
    $$\pi(a|s) = 
    \begin{cases}
  1  & if a = \arg\max_a (R_{s}^{a} + \sum P_{ss^{'}}^{a}v_{\pi}(s^{'}))\\    
  0 & else    
\end{cases} $$


In [2]:
def valueIteration(env,gamma,num_iters):
    num_states = env.observation_space.n
    num_actions = env.action_space.n

    # Initialize state value function
    state_value_function = np.zeros(num_states)    
    
    def Q_calculation(state_value_function):
        q_s_a = np.zeros((num_states,num_actions))
        for state in range(num_states):
            for action in range(num_actions):
                state_action = env.unwrapped.P[state][action]
                next_states = [state_action[i][1] for i in range(len(state_action))]
                prob = [state_action[i][0] for i in range(len(state_action))]
                reward = [state_action[i][2] for i in range(len(state_action))]
                q_s_a[state,action] = np.dot(prob,gamma*state_value_function[next_states]+reward)
        return q_s_a
                
    def updateValueFunction(q_s_a):
        state_value_function = np.max(q_s_a,1)
        return state_value_function
    
    def findPolicy(state_value_function):
        q_s_a = Q_calculation(state_value_function)
        policy = np.eye(num_actions)[np.argmax(q_s_a,1)]
        return policy 
    
    for i in range(num_iters):
        q_s_a = Q_calculation(state_value_function)
        state_value_function = updateValueFunction(q_s_a)
        
    policy = findPolicy(state_value_function)
    
    return policy


# Load Stochastic Frozenlake and find Policy using value iteration

In [3]:
env_slip = gym.make('FrozenLake-v0')    
gamma = 0.9
num_iters = 100
env_slip.reset()
env_slip.render()
policy_slip_valurIteration = valueIteration(env_slip,gamma,num_iters)
print('policy : \n',policy_slip_valurIteration)


SFFF
FHFH
FFFH
HFFG
policy : 
 [[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


# Play Stochastic Frozenlake with the policy determined from value iteration

In [4]:
env_slip.reset()
cur_state = 0
termination = False
while(not termination):
    action = np.argmax(policy_slip_valurIteration[cur_state,:])    
    cur_state, reward, termination, info = env_slip.step(action)
    print(action,cur_state,reward)
    env_slip.render()

0 0 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
0 0 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
0 4 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
0 4 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
0 4 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
0 8 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
3 8 0.0
  (Up)
SFFF
FHFH
FFFH
HFFG
3 8 0.0
  (Up)
SFFF
FHFH
FFFH
HFFG
3 9 0.0
  (Up)
SFFF
FHFH
FFFH
HFFG
1 10 0.0
  (Down)
SFFF
FHFH
FFFH
HFFG
0 14 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
1 15 1.0
  (Down)
SFFF
FHFH
FFFH
HFFG


# Load Deterministic Frozenlake and find Policy using value iteration

In [5]:
from gym.envs.registration import register
register(
    id='FrozenLakeNotSlippery-v0',
    entry_point='gym.envs.toy_text:FrozenLakeEnv',
    kwargs={'map_name' : '4x4', 'is_slippery': False},
    max_episode_steps=100,
    reward_threshold=0.78, # optimum = .8196
) 


In [6]:
env_no_slip = gym.make('FrozenLakeNotSlippery-v0')
gamma = 0.9
num_iters = 100
env_no_slip.reset()
env_no_slip.render()
policy_valueIteration = valueIteration(env_no_slip,gamma,num_iters)
print(policy_valueIteration)


SFFF
FHFH
FFFH
HFFG
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]


# Play Deterministic Frozenlake with the policy determined from value iteration

In [7]:
env_no_slip.reset()
env_no_slip.render()
cur_state = 0
termination = False
while(not termination):
    action = np.argmax(policy_valueIteration[cur_state,:])    
    cur_state, reward, termination, info = env_no_slip.step(action)
    print(action,cur_state,reward)
    env_no_slip.render()


SFFF
FHFH
FFFH
HFFG
1 4 0.0
  (Down)
SFFF
FHFH
FFFH
HFFG
1 8 0.0
  (Down)
SFFF
FHFH
FFFH
HFFG
2 9 0.0
  (Right)
SFFF
FHFH
FFFH
HFFG
1 13 0.0
  (Down)
SFFF
FHFH
FFFH
HFFG
2 14 0.0
  (Right)
SFFF
FHFH
FFFH
HFFG
2 15 1.0
  (Right)
SFFF
FHFH
FFFH
HFFG


# Policy Iteration
Steps: <br>
1. Initialize Policy Function <br>
2. Repeat <br>
    a. Find value function from policy function. <br> This has a fixed solution which is $V = (1-{\gamma}P)^{-1}R$ where $\gamma$ is the discount factor, P is the transition probabiity matrix of a Markov Decision Process and R is Rewards.  But as this solution invloves matrix inverse calculation which is computationally expensive, we use an iterative procedure to find value function. <br> <br> Repeat (until $V_{\pi}^{updated}(s)=V_{\pi}(s)$) 
    $$V_{\pi}^{updated}(s) =  R_{s}^{a} + \sum P_{ss^{'}}^{a}v_{\pi}(s^{'})$$ where a is the action taken in state s based on policy
    
    b. Find Policy from value function <br>
    $$\pi(a|s) = 
    \begin{cases}
  1  & if a = \arg\max_a (R_{s}^{a} + \sum P_{ss^{'}}^{a}v_{\pi}(s^{'}))\\    
  0 & else    
\end{cases} $$

In [8]:
def policyIteration(env,gamma,num_iters):
    num_states = env.observation_space.n
    num_actions = env.action_space.n
    
    def findValueFunction(policy):
        max_iters_VF = 1000
        thresold = 0.000001
        delta = thresold+1
        state_value_function = np.zeros(num_states)#np.random.randn(num_states)
        state_value_function_new = np.zeros(num_states)
        iter_num = 0
        # Synchronous Update 
        while(delta>thresold and iter_num<max_iters_VF):
            state_value_function_new = np.zeros(num_states)
            for state in range(num_states):
                action = np.argmax(policy[state])
                state_action = env.unwrapped.P[state][action]
                next_states = [state_action[i][1] for i in range(len(state_action))]
                prob = [state_action[i][0] for i in range(len(state_action))]
                reward = [state_action[i][2] for i in range(len(state_action))]                
                state_value_function_new[state] = (np.dot(prob,gamma*state_value_function[next_states]+reward))  
            delta = np.linalg.norm(state_value_function_new-state_value_function)  
            state_value_function = state_value_function_new
            iter_num += 1
        return state_value_function
                
    def updatePolicy(state_value_function):
        q_s_a = np.zeros((num_states,num_actions))
        for state in range(num_states):
            for action in range(num_actions):
                state_action = env.unwrapped.P[state][action]
                next_states = [state_action[i][1] for i in range(len(state_action))]
                prob = [state_action[i][0] for i in range(len(state_action))]
                reward = [state_action[i][2] for i in range(len(state_action))]
                q_s_a[state,action] = gamma*np.dot(prob,state_value_function[next_states])+np.dot(prob,reward)
        policy = np.eye(num_actions)[np.argmax(q_s_a,1)]
        return policy
    
    iter_num = 0
    delta = 1
    # Initialize policy function
    policy = np.eye(num_actions)[np.random.randint(0,num_actions,num_states)]
    while(delta>0 and iter_num<num_iters):
        print(iter_num)
        print(policy)
        state_value_function = findValueFunction(policy)
        policy_new = updatePolicy(state_value_function)
        delta = np.linalg.norm(policy_new-policy)
        policy = policy_new
        iter_num += 1
        
    return policy


# Load Stochastic Frozenlake and find Policy using policy iteration

In [9]:
env_slip = gym.make('FrozenLake-v0')    
gamma = 0.9
num_iters = 100
env_slip.reset()
env_slip.render()
policy_slip_policyIteration = policyIteration(env_slip,gamma,num_iters)
print(policy_slip_policyIteration)


SFFF
FHFH
FFFH
HFFG
0
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
1
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
2
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


# Play Stochastic Frozenlake with the policy determined from policy iteration

In [10]:
env_slip.reset()
cur_state = 0
termination = False
while(not termination):
    action = np.argmax(policy_slip_policyIteration[cur_state,:])    
    cur_state, reward, termination, info = env_slip.step(action)
    print(action,cur_state,reward)
    env_slip.render()

0 4 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
0 0 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
0 4 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
0 8 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
3 4 0.0
  (Up)
SFFF
FHFH
FFFH
HFFG
0 0 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
0 0 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
0 0 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
0 0 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
0 4 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
0 4 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
0 8 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
3 4 0.0
  (Up)
SFFF
FHFH
FFFH
HFFG
0 0 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
0 4 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
0 8 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
3 8 0.0
  (Up)
SFFF
FHFH
FFFH
HFFG
3 9 0.0
  (Up)
SFFF
FHFH
FFFH
HFFG
1 8 0.0
  (Down)
SFFF
FHFH
FFFH
HFFG
3 8 0.0
  (Up)
SFFF
FHFH
FFFH
HFFG
3 4 0.0
  (Up)
SFFF
FHFH
FFFH
HFFG
0 4 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
0 8 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
3 9 0.0
  (Up)
SFFF
FHFH
FFFH
HFFG
1 8 0.0
  (Down)
SFFF
FHFH
FFFH
HFFG
3 4 0.0
  (Up)
SFFF
FHFH
FFFH
HFFG
0 0 0.0
  (Left)
SFFF
FHFH
FFFH
HFFG
0 0 0.0
  (Left)


# Load Deterministic Frozenlake and find Policy using policy iteration

In [11]:
env_no_slip = gym.make('FrozenLakeNotSlippery-v0')
gamma = 0.9
num_iters = 100
env_no_slip.reset()
env_no_slip.render()
policy_policyIteration = policyIteration(env_no_slip,gamma,num_iters)
print(policy_policyIteration)


SFFF
FHFH
FFFH
HFFG
0
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
1
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
2
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
3
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
4
[[1. 

# Play Deterministic Frozenlake with the policy determined from policy iteration

In [12]:
env_no_slip.reset()
cur_state = 0
termination = False
while(not termination):
    action = np.argmax(policy_policyIteration[cur_state,:])    
    cur_state, reward, termination, info = env_no_slip.step(action)
    print(action,cur_state,reward)
    env_no_slip.render()

1 4 0.0
  (Down)
SFFF
FHFH
FFFH
HFFG
1 8 0.0
  (Down)
SFFF
FHFH
FFFH
HFFG
2 9 0.0
  (Right)
SFFF
FHFH
FFFH
HFFG
1 13 0.0
  (Down)
SFFF
FHFH
FFFH
HFFG
2 14 0.0
  (Right)
SFFF
FHFH
FFFH
HFFG
2 15 1.0
  (Right)
SFFF
FHFH
FFFH
HFFG
